#!/bin/bash

readonly TARGET_DIR="/media/sf_Dropbox/backups/LinuxStuff"

readonly TARGET_FILE_NAME_PREFIX="myLinuxStuff_"
readonly TARGET_FILE_NAME_TIMESTAMP="$(date +%Y_%m_%d)"
readonly TARGET_FILE_NAME="${TARGET_FILE_NAME_PREFIX}${TARGET_FILE_NAME_TIMESTAMP}.tar.gz"